### ISSUE TITLE
esd protection is missing on usb 

### ISSUE THREAD

**Issue by lllaaa** [canokeys/canokey-hardware#4]

**Comment by z4yx** [comment]
STM32 features built-in ESD protection.
![image](https://user-images.githubusercontent.com/2733275/154499092-53e091bc-6f19-432e-9af0-bda9dca3360f.png)

**Comment by z4yx** [comment]
When you touch the key while it's plugged, a severe static discharge from the human body to the ground can happen. So we add an extra diode to enhance the protection level.
